# Use the official NGINX base image
FROM nginx:alpine

# Copy static website files to the NGINX web directory
COPY .github/workflows/html /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
