name: first-workflow
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome to first workflow 
        run: echo "testing"
      
      - name: echoing
        run: echo "building"

      - name: deploy
        run: echo "Deployment done"
