name: first-workflow
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Building
              env:
                Name: Docker-username
              run: |
                echo ${{env.Name}}
                sleep 30


    second-job:
        needs: first-job
        runs-on : ubuntu-latest
        steps:
            - name: deploying
              run: |
                echo "deploying"
                sleep 30