name: first-workflow
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Building
            run: |
                echo "Building"
                sleep 30
    second-job:
        runs-on : ubuntu-latest
        steps:
            - name: deploying
            run: |
                echo "building"
                sleep 30